version: "3.9"
services:
  scanner:
    build: .
    image: cfd-trader-assistant:latest
    env_file:
      - .env
    volumes:
      - ./:/app
    command: ["python", "main.py", "scan", "--mode=intraday"]
    restart: unless-stopped

  dashboard:
    build: .
    image: cfd-trader-assistant:latest
    env_file:
      - .env
    volumes:
      - ./:/app
    ports:
      - "8501:8501"
    command: ["streamlit", "run", "app/dashboard.py", "--server.port", "8501", "--server.address", "0.0.0.0"]
    restart: unless-stopped
