trend:
  sma_long: 200
  sma_mid: 50
  sma_fast: 20

entry:
  donchian_period: 20
  roc_lookback: 10
  roc_min_long: 0.003
  roc_max_short: -0.003

quality:
  vol_mult: 1.2
  atr_min_pct: 0.003
  atr_max_pct: 0.03

risk:
  stop_atr_mult: 1.5
  rr_ratio: 2.0
  time_stop_bars: 12
  max_open_signals: 5
  risk_per_trade_pct: 0.008
  max_daily_loss_pct: 0.02

cooldowns:
  per_symbol_minutes: 30

filters:
  macro:
    enabled: true
    no_trade_minutes_before: 30
    no_trade_minutes_after: 30
